INSERT INTO schools (name, city, district, board, type, address, website, contact) VALUES
('D.A.V. Public School', 'Bhubaneswar', 'Khordha', 'CBSE', 'Private', 'Unit VIII, Bhubaneswar', 'http://www.davbbsr.org', '0674-2531001'),
('Sainik School', 'Bhubaneswar', 'Khordha', 'CBSE', 'Public', 'Sainik School, Bhubaneswar', 'http://www.sainikschoolbhubaneswar.org', '0674-2582181'),
('Kendriya Vidyalaya No.1', 'Bhubaneswar', 'Khordha', 'CBSE', 'Public', 'Unit IX, Bhubaneswar', 'http://www.kv1bbsr.org', '0674-2531742'),
('St. Joseph''s High School', 'Cuttack', 'Cuttack', 'ICSE', 'Private', 'Buxi Bazar, Cuttack', 'http://www.stjosephscuttack.com', '0671-2305452'),
('Ravenshaw Collegiate School', 'Cuttack', 'Cuttack', 'State', 'Public', 'College Square, Cuttack', 'http://www.ravenshawcollegiateschool.edu.in', '0671-2605355'),
('Stewart School', 'Cuttack', 'Cuttack', 'ICSE', 'Private', 'Buxi Bazar, Cuttack', 'http://www.stewartschoolctc.org', '0671-2305452'),
('Emmanuel School', 'Berhampur', 'Ganjam', 'CBSE', 'Private', 'Near Aska Road, Berhampur', 'http://www.emmanuelschoolberhampur.com', '0680-2290456'),
('Khallikote Union High School', 'Berhampur', 'Ganjam', 'State', 'Public', 'Khallikote Colony, Berhampur', 'http://www.khallikoteunion.edu.in', '0680-2290123'),
('DAV Public School', 'Berhampur', 'Ganjam', 'CBSE', 'Private', 'S.N. College Road, Berhampur', 'http://www.davberhampur.org', '0680-2290789'),
('Jawahar Navodaya Vidyalaya', 'Rayagada', 'Rayagada', 'CBSE', 'Public', 'Rayagada, Odisha', 'http://www.jnvrayagada.org', '06856-235678'),
('St. Mary''s School', 'Rourkela', 'Sundargarh', 'ICSE', 'Private', 'Udit Nagar, Rourkela', 'http://www.stmarysrkl.org', '0661-2543210'),
('Ispat English Medium School', 'Rourkela', 'Sundargarh', 'CBSE', 'Private', 'Sector-19, Rourkela', 'http://www.iemsrkl.org', '0661-2654321'),
('Kendriya Vidyalaya', 'Rourkela', 'Sundargarh', 'CBSE', 'Public', 'Sector-6, Rourkela', 'http://www.kvrourkela.org', '0661-2547890'),
('St. Vincent''s Convent School', 'Balasore', 'Balasore', 'ICSE', 'Private', 'Mission Compound, Balasore', 'http://www.stvincentsbalasore.org', '06782-262456'),
('Fakir Mohan High School', 'Balasore', 'Balasore', 'State', 'Public', 'Nua Bazar, Balasore', 'http://www.fakiramohanschool.edu.in', '06782-260123'),
('DAV Public School', 'Balasore', 'Balasore', 'CBSE', 'Private', 'Ramanagar, Balasore', 'http://www.davbalasore.org', '06782-264567'),
('Saraswati Sishu Vidya Mandir', 'Puri', 'Puri', 'State', 'Private', 'Grand Road, Puri', 'http://www.ssvmpuri.org', '06752-223456'),
('Emmanuel English Medium School', 'Puri', 'Puri', 'CBSE', 'Private', 'Sea Beach Road, Puri', 'http://www.emmanuelpuri.org', '06752-228901'),
('Christ College School', 'Cuttack', 'Cuttack', 'ICSE', 'Private', 'Jobra, Cuttack', 'http://www.christcollegecuttack.org', '0671-2543210'),
('St. Xavier''s High School', 'Bhubaneswar', 'Khordha', 'ICSE', 'Private', 'C.R.P.F Square, Bhubaneswar', 'http://www.stxaviersbbsr.org', '0674-2547890'),
('Mother''s Public School', 'Bhubaneswar', 'Khordha', 'CBSE', 'Private', 'Unit IX, Bhubaneswar', 'http://www.motherspublicschool.org', '0674-2534567'),
('Buxi Jagabandhu English Medium School', 'Bhubaneswar', 'Khordha', 'State', 'Public', 'Bapuji Nagar, Bhubaneswar', 'http://www.bjems.org', '0674-2540123'),
('Odisha Adarsha Vidyalaya', 'Bhubaneswar', 'Khordha', 'State', 'Public', 'Nayapalli, Bhubaneswar', 'http://www.oav.edu.in', '0674-2567890'),
('Delhi Public School', 'Bhubaneswar', 'Khordha', 'CBSE', 'Private', 'Patia, Bhubaneswar', 'http://www.dpsbbsr.org', '0674-2725555'),
('Sai International School', 'Bhubaneswar', 'Khordha', 'CBSE', 'Private', 'Sai Nagar, Bhubaneswar', 'http://www.saiinternational.edu.in', '0674-7100000');